name: private_messaging
description: App di messaggistica privata con crittografia E2E
publish_to: 'none'
version: 1.6.0+7


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5

  # Networking
  http: ^1.6.0

  # Storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  sqflite: ^2.3.0
  path: ^1.9.0

  # Encryption
  pointycastle: ^3.9.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  asn1lib: ^1.5.0

  # Firebase (aggiornate alle ultime versioni)
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  flutter_local_notifications: ^19.5.0

  # UI
  flutter_chat_ui: ^2.11.1
  intl: ^0.20.2
  uuid: ^4.2.2
  timezone: ^0.10.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4

  # File Picking & Media
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  file_picker: ^8.1.6
  mime: ^1.0.6
  path_provider: ^2.1.5
  image: ^4.1.7
  open_filex: ^4.5.0
  pdfx: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
